name: 'Notion Pages'
description: 'Generate markdown files in _posts folder from Notion pages.'
author: 'Bendy Zhang'
inputs:
  notion-token:
    required: true
    description: 'Notion access token'
  root-page-id:
    required: true
    description: 'root page id'
  output-dir:
    required: false
    description: 'output folder'
    default: './_posts/'
  cleanup-before:
    required: false
    description: 'remove all files in output directory'
    default: false


branding:
  icon: 'archive'
  color: 'orange'

runs:
  using: 'node16'
  main: 'dist/index.js'
