name: 'Notion Pages'
description: 'Generate Markdown files in the Docusaurus blog folder from Notion pages.'
author: 'Bendy Zhang'
inputs:
  notion-token:
    required: true
    description: 'Notion access token'
  root-page-id:
    required: true
    description: 'root page id'
  output-dir:
    required: false
    description: 'output folder (default ./blog/ for Docusaurus blog)'
    default: './blog/'
  cleanup-before:
    required: false
    description: 'remove all files in output directory'
    default: 'false'
  output-page-count:
    required: false
    description: 'limit the number of pages exported (0 means no limit)'
    default: '0'


branding:
  icon: 'archive'
  color: 'orange'

runs:
  using: 'node20'
  main: 'dist/index.js'
